- [ ] Be well-tested according to our Automated Testing Policy, and the test suite must be passing.
- [ ] Conform to the Ruby Community Styleguide via rubocop.
- [ ] Update the seed file with any new data that QA will need to accept your feature
- [ ] Ensure that any new ENV vars are added to `.env.example` and updated on CI and servers
- [ ] Views render correctly in all supported browsers
- [ ] New images are compressed
- [ ] New dependencies are appropriately licensed as per our MSA with the client (ask if you don't know)
- [ ] If this code involves sensitive data like PII, credit card, or bank info, ensure that it is properly safeguarded
